import type { NextConfig } from "next";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

/**
 * 301s for Beehiiv slugs with broken accents (generated by scripts/sync-content.ts).
 * /p/inauguraci-n-...  ->  /p/inauguracion-...
 */
function slugRedirects() {
  const file = path.join(process.cwd(), "content", "cache", "redirects.json");
  if (!existsSync(file)) return [];
  const map = JSON.parse(readFileSync(file, "utf8")) as Record<string, string>;
  return Object.entries(map).map(([from, to]) => ({
    source: `/p/${from}`,
    destination: `/p/${to}`,
    statusCode: 301 as const,
  }));
}

const nextConfig: NextConfig = {
  poweredByHeader: false,
  images: {
    loader: "custom",
    loaderFile: "./src/lib/image-loader.ts",
    deviceSizes: [640, 828, 1080, 1440, 2048],
    imageSizes: [96, 160, 256, 384],
  },
  async redirects() {
    return [
      ...slugRedirects(),
      { source: "/feed", destination: "/feed.xml", statusCode: 301 },
      { source: "/rss", destination: "/feed.xml", statusCode: 301 },
      { source: "/posts", destination: "/archive", statusCode: 301 },
      { source: "/archivo", destination: "/archive", statusCode: 301 },
    ];
  },
  async rewrites() {
    // Directory indexes that vanilla Vercel static hosting served automatically.
    return [
      { source: "/index.html", destination: "/" },
      { source: "/brand", destination: "/brand.html" },
      { source: "/hub", destination: "/hub/index.html" },
      { source: "/hub/", destination: "/hub/index.html" },
      { source: "/resources", destination: "/resources/index.html" },
      { source: "/resources/", destination: "/resources/index.html" },
      { source: "/resources/tools/:slug", destination: "/resources/tool.html" },
      { source: "/ops/merch", destination: "/ops/merch/index.html" },
      { source: "/ops/merch/", destination: "/ops/merch/index.html" },
      { source: "/ops/stellar", destination: "/ops/stellar/index.html" },
      { source: "/ops/stellar/", destination: "/ops/stellar/index.html" },
      { source: "/ops/social", destination: "/ops/social/index.html" },
      { source: "/ops/social/", destination: "/ops/social/index.html" },
      { source: "/ops/tierly", destination: "/ops/tierly/index.html" },
      { source: "/ops/tierly/", destination: "/ops/tierly/index.html" },
      { source: "/tools/qr-generator", destination: "/ops/social/index.html" },
      { source: "/tools/fear-greed", destination: "/tools/fear-greed/index.html" },
      { source: "/tools/fear-greed/", destination: "/tools/fear-greed/index.html" },
      { source: "/merch", destination: "/merch/index.html" },
      { source: "/merch/", destination: "/merch/index.html" },
      { source: "/stellar", destination: "/stellar/index.html" },
      { source: "/stellar/", destination: "/stellar/index.html" },
    ];
  },
};

export default nextConfig;
