-- Keep Stellar Chile deliverables aligned with the signed SOW, Exhibit A, Section 4.
update public.deliverables d set description = case
  when d.title = 'Plan de lanzamiento' then
    'Chapter Launch Plan — Written plan outlining how the Service Provider will achieve the KPIs in Section 5, including: (i) proposed event calendar; (ii) ambassador recruitment and outreach strategy; (iii) developer engagement strategy; (iv) ecosystem partnership strategy; and (v) Instaward and SCF pipeline development approach. Delivery: written submission to Company POC. Acceptance: submitted by due date; addresses each KPI category in Section 5; accepted by the Company.'
  when d.title like 'Entregables mensuales — %' then
    'Community Events — Event Documentation Packages evidencing a minimum of three (3) Qualifying Events, including: (i) event agenda; (ii) attendance records; (iii) photographs, screenshots, or other evidence of event execution; (iv) event summary; and (v) outcomes achieved. Educational and Developer Content Deliverables — evidence of publication of a minimum of two (2) original content pieces. SCF Project Referrals — documentation of a minimum of two (2) SCF referrals submitted through Company-designated processes. Instaward Identifications — documentation of a minimum of three (3) eligible Instaward candidate submissions through Company-designated processes. Monthly Activity Report — covering: (i) ambassador recruitment activities and current chapter roster; (ii) Qualifying Events; (iii) developer engagement and onboarding; (iv) SCF referral pipeline; (v) Instaward candidate pipeline; (vi) ecosystem partnership outreach and partnerships established; and (vii) planned initiatives for the following month. Delivery: Airtable and Monthly Activity Report submission to Company POC. Acceptance: submitted by due date, all required documentation and sections included, and activity data consistent with Airtable records.'
  when d.title = 'Validación KPI — meses 1 a 3' then
    'Quarterly KPI Validation Report (Month 3) — Comprehensive KPI validation report evidencing performance against each KPI category in Section 5, supported by: (i) ambassador onboarding records; (ii) event documentation; (iii) developer engagement records; (iv) SCF referral records; (v) Instaward records; and (vi) ecosystem partnership documentation. Delivery: Airtable and written submission to Company POC. Acceptance: all KPI categories addressed and supporting documentation sufficient to validate reported figures.'
  when d.title = 'Validación KPI — meses 4 a 6' then
    'Quarterly KPI Validation Report (Month 6) — Comprehensive KPI validation report evidencing performance against each KPI category in Section 5, supported by: (i) ambassador onboarding records; (ii) event documentation; (iii) developer engagement records; (iv) SCF referral records; (v) Instaward records; and (vi) ecosystem partnership documentation. Delivery: Airtable and written submission to Company POC. Acceptance: all KPI categories addressed and supporting documentation sufficient to validate reported figures.'
  when d.title = 'Paquete de transición' then
    'End-of-Term Transition Package — Final chapter status report including: (i) current ambassador roster and tier status; (ii) inventory of Program accounts, assets, and access credentials; (iii) outstanding third-party commitments; (iv) status of ecosystem partnerships; and (v) transition recommendations and handover notes for any successor service provider. Delivery: written submission to Company POC. Acceptance: all required information provided and any requested materials transferred to the Company.'
  else d.description
end
from public.programs p
where d.program_id = p.id and p.code = 'stellar_chile';
